<?php
/**
 * File: admin_edit_soal.php
  * Halaman untuk Admin mengedit detail sebuah soal dari bank soal.
   */

   require_once 'config/koneksi.php';

   // Keamanan: Pastikan hanya ADMIN yang bisa akses
   if (!isset($_SESSION['user_id']) || $_SESSION['peran'] != 'admin') {
       header("Location: logout.php");
           exit();
           }
           $id_admin = $_SESSION['user_id'];
           $pesan = '';

           // Validasi ID Soal dari URL
           if (!isset($_GET['id'])) {
               header("Location: admin_bank_soal.php");
                   exit();
                   }
                   $id_soal = intval($_GET['id']);

                   // Logika untuk menyimpan perubahan
                   if ($_SERVER['REQUEST_METHOD'] == 'POST' && isset($_POST['edit_soal_submit'])) {
                       $mapel_edit = sanitize($koneksi, $_POST['mapel_edit']);
                           $soal_edit = $_POST['soal_edit']; // Dari CKEditor
                               $tipe_soal_edit = sanitize($koneksi, $_POST['tipe_soal_edit']);

                                   if ($tipe_soal_edit === 'pilihan_ganda') {
                                           $opsi_a_edit = sanitize($koneksi, $_POST['opsi_a_edit']);
                                                   $opsi_b_edit = sanitize($koneksi, $_POST['opsi_b_edit']);
                                                           $opsi_c_edit = sanitize($koneksi, $_POST['opsi_c_edit']);
                                                                   $opsi_d_edit = sanitize($koneksi, $_POST['opsi_d_edit']);
                                                                           $opsi_e_edit = sanitize($koneksi, $_POST['opsi_e_edit']);
                                                                                   $kunci_edit = sanitize($koneksi, $_POST['kunci_jawaban_edit']);
                                                                                           $skor_edit = intval($_POST['skor_edit']);

                                                                                                   $stmt_update = $koneksi->prepare("UPDATE bank_soal SET mapel=?, soal=?, opsi_a=?, opsi_b=?, opsi_c=?, opsi_d=?, opsi_e=?, kunci_jawaban=?, skor=? WHERE id=?");
                                                                                                           $stmt_update->bind_param("ssssssssii", $mapel_edit, $soal_edit, $opsi_a_edit, $opsi_b_edit, $opsi_c_edit, $opsi_d_edit, $opsi_e_edit, $kunci_edit, $skor_edit, $id_soal);
                                                                                                               } else { // Esai
                                                                                                                       $stmt_update = $koneksi->prepare("UPDATE bank_soal SET mapel=?, soal=? WHERE id=?");
                                                                                                                               $stmt_update->bind_param("ssi", $mapel_edit, $soal_edit, $id_soal);
                                                                                                                                   }

                                                                                                                                       if ($stmt_update->execute()) {
                                                                                                                                               header("Location: admin_bank_soal.php?status=sukses_edit");
                                                                                                                                                       exit();
                                                                                                                                                           } else {
                                                                                                                                                                   $pesan = "<div class='alert alert-danger'>Gagal memperbarui soal. Error: " . htmlspecialchars($stmt_update->error) . "</div>";
                                                                                                                                                                       }
                                                                                                                                                                           $stmt_update->close();
                                                                                                                                                                           }


                                                                                                                                                                           // Ambil data soal terkini untuk ditampilkan di form
                                                                                                                                                                           $stmt_data = $koneksi->prepare("SELECT * FROM bank_soal WHERE id = ?");
                                                                                                                                                                           $stmt_data->bind_param("i", $id_soal);
                                                                                                                                                                           $stmt_data->execute();
                                                                                                                                                                           $result_data = $stmt_data->get_result();
                                                                                                                                                                           if ($result_data->num_rows == 0) {
                                                                                                                                                                               header("Location: admin_bank_soal.php?status=gagal");
                                                                                                                                                                                   exit();
                                                                                                                                                                                   }
                                                                                                                                                                                   $soal = $result_data->fetch_assoc();
                                                                                                                                                                                   $stmt_data->close();

                                                                                                                                                                                   include_once 'templates/header_admin.php';
                                                                                                                                                                                   ?>
                                                                                                                                                                                   <script src="https://cdn.ckeditor.com/4.22.1/full-all/ckeditor.js"></script>

                                                                                                                                                                                   <nav aria-label="breadcrumb">
                                                                                                                                                                                       <ol class="breadcrumb">
                                                                                                                                                                                               <li class="breadcrumb-item"><a href="admin_dashboard.php">Dashboard</a></li>
                                                                                                                                                                                                       <li class="breadcrumb-item"><a href="admin_bank_soal.php">Bank Soal Terpusat</a></li>
                                                                                                                                                                                                               <li class="breadcrumb-item active" aria-current="page">Edit Soal</li>
                                                                                                                                                                                                                   </ol>
                                                                                                                                                                                                                   </nav>

                                                                                                                                                                                                                   <h1><i class="bi bi-pencil-square me-2"></i>Edit Soal</h1>
                                                                                                                                                                                                                   <hr>

                                                                                                                                                                                                                   <?php if(!empty($pesan)) echo $pesan; ?>

                                                                                                                                                                                                                   <div class="card">
                                                                                                                                                                                                                       <div class="card-body">
                                                                                                                                                                                                                               <form action="admin_edit_soal.php?id=<?php echo $id_soal; ?>" method="POST" id="form-edit">
                                                                                                                                                                                                                                           <input type="hidden" name="edit_soal_submit" value="1">
                                                                                                                                                                                                                                                       <input type="hidden" name="tipe_soal_edit" value="<?php echo $soal['tipe_soal']; ?>">

                                                                                                                                                                                                                                                                   <div class="mb-3">
                                                                                                                                                                                                                                                                                   <label class="form-label fw-bold">Mata Pelajaran</label>
                                                                                                                                                                                                                                                                                                   <input type="text" name="mapel_edit" class="form-control" value="<?php echo htmlspecialchars($soal['mapel']); ?>" required>
                                                                                                                                                                                                                                                                                                               </div>
                                                                                                                                                                                                                                                                                                                           <div class="mb-3">
                                                                                                                                                                                                                                                                                                                                           <label class="form-label fw-bold">Pertanyaan</label>
                                                                                                                                                                                                                                                                                                                                                           <textarea name="soal_edit" id="editor_edit" class="form-control" rows="8"><?php echo htmlspecialchars($soal['soal']); ?></textarea>
                                                                                                                                                                                                                                                                                                                                                                       </div>

                                                                                                                                                                                                                                                                                                                                                                                   <?php if ($soal['tipe_soal'] === 'pilihan_ganda'): ?>
                                                                                                                                                                                                                                                                                                                                                                                               <div id="kolom-pilihan-ganda-edit">
                                                                                                                                                                                                                                                                                                                                                                                                               <hr>
                                                                                                                                                                                                                                                                                                                                                                                                                               <div class="row g-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                   <div class="col-md-6"><label class="form-label">Opsi A</label><input type="text" name="opsi_a_edit" class="form-control" value="<?php echo htmlspecialchars($soal['opsi_a']); ?>"></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <div class="col-md-6"><label class="form-label">Opsi B</label><input type="text" name="opsi_b_edit" class="form-control" value="<?php echo htmlspecialchars($soal['opsi_b']); ?>"></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           <div class="col-md-6"><label class="form-label">Opsi C</label><input type="text" name="opsi_c_edit" class="form-control" value="<?php echo htmlspecialchars($soal['opsi_c']); ?>"></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               <div class="col-md-6"><label class="form-label">Opsi D</label><input type="text" name="opsi_d_edit" class="form-control" value="<?php echo htmlspecialchars($soal['opsi_d']); ?>"></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <div class="col-md-6"><label class="form-label">Opsi E</label><input type="text" name="opsi_e_edit" class="form-control" value="<?php echo htmlspecialchars($soal['opsi_e']); ?>"></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <div class="col-md-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               <label class="form-label">Kunci Jawaban</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <select name="kunci_jawaban_edit" class="form-select">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <?php foreach(['A', 'B', 'C', 'D', 'E'] as $opt): ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <option value="<?php echo $opt; ?>" <?php if($soal['kunci_jawaban'] == $opt) echo 'selected'; ?>><?php echo $opt; ?></option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               <?php endforeach; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               <div class="col-md-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <label class="form-label">Skor</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               <input type="number" name="skor_edit" class="form-control" value="<?php echo htmlspecialchars($soal['skor']); ?>" required>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           <?php endif; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <div class="mt-4 text-end">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <a href="admin_bank_soal.php" class="btn btn-secondary">Batal</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <button type="submit" class="btn btn-primary">Simpan Perubahan</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           <script>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               CKEDITOR.replace('editor_edit', {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       fullPage: false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               allowedContent: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       height: 250
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               document.querySelector('#form-edit').addEventListener('submit', () => CKEDITOR.instances.editor_edit.updateElement());
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               </script>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               <?php
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               $koneksi->close();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               include_once 'templates/footer_admin.php';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ?>