<?php
/**
 * File: admin_pengumuman.php
  * Versi FINAL dengan Detektif Error
   */

    require_once 'config/koneksi.php';

   // Keamanan: Pastikan hanya ADMIN yang bisa akses
   if (!isset($_SESSION['user_id']) || $_SESSION['peran'] != 'admin') {
       header("Location: logout.php");
           exit();
           }
           $id_admin = $_SESSION['user_id'];
           $pesan = '';

           // Logika untuk membuat pengumuman baru
           if ($_SERVER['REQUEST_METHOD'] == 'POST' && isset($_POST['buat_pengumuman'])) {
               $judul = sanitize($koneksi, $_POST['judul']);
                   $isi = $_POST['isi']; // Biarkan HTML dari editor

                       if (!empty($judul) && !empty($isi)) {
                               $stmt = $koneksi->prepare("INSERT INTO pengumuman (judul, isi, id_admin) VALUES (?, ?, ?)");
                                       $stmt->bind_param("ssi", $judul, $isi, $id_admin);
                                               if ($stmt->execute()) {
                                                           $pesan = "<div class='alert alert-success alert-dismissible fade show' role='alert'>Pengumuman baru berhasil dibuat.<button type='button' class='btn-close' data-bs-dismiss='alert'></button></div>";
                                                                   } else {
                                                                               $pesan = "<div class='alert alert-danger alert-dismissible fade show' role='alert'>Gagal membuat pengumuman.<button type='button' class='btn-close' data-bs-dismiss='alert'></button></div>";
                                                                                       }
                                                                                               $stmt->close();
                                                                                                   } else {
                                                                                                           $pesan = "<div class='alert alert-warning alert-dismissible fade show' role='alert'>Judul dan isi pengumuman tidak boleh kosong.<button type='button' class='btn-close' data-bs-dismiss='alert'></button></div>";
                                                                                                               }
                                                                                                               }

                                                                                                               // Logika untuk menghapus pengumuman
                                                                                                               if (isset($_GET['aksi']) && $_GET['aksi'] == 'hapus' && isset($_GET['id'])) {
                                                                                                                   $id_pengumuman = intval($_GET['id']);
                                                                                                                       $stmt_hapus = $koneksi->prepare("DELETE FROM pengumuman WHERE id = ?");
                                                                                                                           $stmt_hapus->bind_param("i", $id_pengumuman);
                                                                                                                               if ($stmt_hapus->execute()) {
                                                                                                                                       $pesan = "<div class='alert alert-success alert-dismissible fade show' role='alert'>Pengumuman berhasil dihapus.<button type='button' class='btn-close' data-bs-dismiss='alert'></button></div>";
                                                                                                                                           }
                                                                                                                                               $stmt_hapus->close();
                                                                                                                                               }

                                                                                                                                               // Ambil semua pengumuman
                                                                                                                                               $sql_pengumuman = "SELECT id, judul, isi, tanggal_dibuat FROM pengumuman ORDER BY tanggal_dibuat DESC";
                                                                                                                                               $result_pengumuman = $koneksi->query($sql_pengumuman);

                                                                                                                                               // Penjaga Error #1: Saat mengambil data pengumuman
                                                                                                                                               if ($result_pengumuman === false) {
                                                                                                                                                   die("<h3>Error Fatal!</h3><p>Gagal mengambil data pengumuman. Periksa apakah tabel `pengumuman` sudah ada dan namanya benar.</p><p>Pesan DB: ".htmlspecialchars($koneksi->error)."</p>");
                                                                                                                                                   }


                                                                                                                                                   include_once 'templates/header_admin.php';
                                                                                                                                                   ?>
                                                                                                                                                   <script src="https://cdn.ckeditor.com/4.22.1/standard/ckeditor.js"></script>

                                                                                                                                                   <h1 class="mb-4">Manajemen Pengumuman</h1>
                                                                                                                                                   <?php if(!empty($pesan)) echo $pesan; ?>

                                                                                                                                                   <div class="row g-4">
                                                                                                                                                       <div class="col-md-5">
                                                                                                                                                               <div class="card shadow-sm">
                                                                                                                                                                           <div class="card-header"><h5 class="mb-0">Buat Pengumuman Baru</h5></div>
                                                                                                                                                                                       <div class="card-body">
                                                                                                                                                                                                       <form action="admin_pengumuman.php" method="POST">
                                                                                                                                                                                                                           <div class="mb-3">
                                                                                                                                                                                                                                                   <label for="judul" class="form-label">Judul Pengumuman</label>
                                                                                                                                                                                                                                                                           <input type="text" name="judul" class="form-control" required>
                                                                                                                                                                                                                                                                                               </div>
                                                                                                                                                                                                                                                                                                                   <div class="mb-3">
                                                                                                                                                                                                                                                                                                                                           <label for="isi" class="form-label">Isi Pengumuman</label>
                                                                                                                                                                                                                                                                                                                                                                   <textarea name="isi" id="editor_pengumuman" class="form-control" rows="8"></textarea>
                                                                                                                                                                                                                                                                                                                                                                                       </div>
                                                                                                                                                                                                                                                                                                                                                                                                           <div class="d-grid">
                                                                                                                                                                                                                                                                                                                                                                                                                                   <button type="submit" name="buat_pengumuman" class="btn btn-primary">Publikasikan</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                       </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <div class="col-md-7">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           <div class="card shadow-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <div class="card-header"><h5 class="mb-0">Daftar Pengumuman</h5></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <div class="list-group list-group-flush" style="max-height: 600px; overflow-y: auto;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <?php if ($result_pengumuman->num_rows > 0): ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <?php while($p = $result_pengumuman->fetch_assoc()): ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           <div class="list-group-item">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <div class="d-flex w-100 justify-content-between">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               <h6 class="mb-1 fw-bold"><?php echo htmlspecialchars($p['judul']); ?></h6>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           <small class="text-muted"><?php echo date('d M Y', strtotime($p['tanggal_dibuat'])); ?></small>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           <div class="mb-2 mt-2 border-start border-3 border-light ps-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <?php echo $p['isi']; // Tidak di-escape karena dari CKEditor ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <a href="admin_pengumuman.php?aksi=hapus&id=<?php echo $p['id']; ?>" class="btn btn-sm btn-outline-danger" onclick="return confirm('Yakin ingin menghapus pengumuman ini?')">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <i class="bi bi-trash-fill"></i> Hapus
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <?php endwhile; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <?php else: ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div class="list-group-item text-center p-4">Belum ada pengumuman.</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <?php endif; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <script>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  CKEDITOR.replace('editor_pengumuman');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </script>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <?php
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  $koneksi->close();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  include_once 'templates/footer_admin.php';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ?>