<?php
/**
 * File: ajax_get_users.php
  * Endpoint AJAX untuk mengambil daftar pengguna terbaru untuk admin dashboard.
   * File ini hanya mengembalikan konten <tbody> dari tabel.
    */

    require_once 'config/koneksi.php';

    // Keamanan: Pastikan hanya ADMIN yang bisa akses
    if (!isset($_SESSION['user_id']) || $_SESSION['peran'] != 'admin') {
        http_response_code(403); // Forbidden
            exit('Akses ditolak.');
            }

            $search_query = "";
            $params = [];
            $types = "";

            // Query dasar untuk mengambil semua pengguna (termasuk no_hp)
            $sql_users = "SELECT id, nama_lengkap, email, no_hp, peran, status_akun FROM pengguna WHERE peran IN ('guru', 'siswa')";

            // Memeriksa apakah ada parameter pencarian 'q'
            if (isset($_GET['q']) && !empty(trim($_GET['q']))) {
                $search_query = trim($_GET['q']);
                    $sql_users .= " AND (nama_lengkap LIKE ? OR email LIKE ?)";
                        $search_param = "%" . $search_query . "%";
                            // Menggunakan call_user_func_array untuk bind_param dinamis
                                $params[] = $search_param;
                                    $params[] = $search_param;
                                        $types .= "ss";
                                        }

                                        $sql_users .= " ORDER BY status_akun DESC, peran, nama_lengkap";
                                        $stmt_users = $koneksi->prepare($sql_users);

                                        // Bind parameter jika ada
                                        if (!empty($params)) {
                                            $stmt_users->bind_param($types, ...$params);
                                            }

                                            $stmt_users->execute();
                                            $result_users = $stmt_users->get_result();

                                            // Cetak baris tabel (TR)
                                            if ($result_users->num_rows > 0) {
                                                while($user = $result_users->fetch_assoc()) {
                                                        $badge_class_peran = $user['peran'] == 'guru' ? 'bg-primary' : 'bg-secondary';
                                                                $status_badge = ($user['status_akun'] == 'aktif') ? "<span class='badge bg-success'>Aktif</span>" : "<span class='badge bg-danger'>Tidak Aktif</span>";
                                                                        $status_action_link = ($user['status_akun'] == 'aktif') ? 
                                                                                    "<a href='ubah_status_akun.php?id={$user['id']}&status_baru=tidak_aktif' class='btn btn-outline-danger'>Nonaktifkan</a>" : 
                                                                                                "<a href='ubah_status_akun.php?id={$user['id']}&status_baru=aktif' class='btn btn-outline-success'>Aktifkan</a>";

                                                                                                        echo "<tr>
                                                                                                                        <td>" . htmlspecialchars($user['nama_lengkap']) . "</td>
                                                                                                                                        <td>" . htmlspecialchars($user['email']) . "</td>
                                                                                                                                                        <td><span class='badge {$badge_class_peran}'>" . ucfirst($user['peran']) . "</span></td>
                                                                                                                                                                        <td>{$status_badge}</td>
                                                                                                                                                                                        <td>
                                                                                                                                                                                                            <div class='btn-group btn-group-sm'>
                                                                                                                                                                                                                                    <a href='admin_login_as.php?id={$user['id']}' class='btn btn-info' onclick=\"return confirm('Anda akan masuk sebagai " . htmlspecialchars($user['nama_lengkap']) . ". Lanjutkan?')\">
                                                                                                                                                                                                                                                                <i class='bi bi-person-bounding-box'></i> Login As
                                                                                                                                                                                                                                                                                        </a>
                                                                                                                                                                                                                                                                                                                <button class='btn btn-success' data-bs-toggle='modal' data-bs-target='#editProfilModal' 
                                                                                                                                                                                                                                                                                                                                            data-user-id='{$user['id']}' 
                                                                                                                                                                                                                                                                                                                                                                        data-user-nama='" . htmlspecialchars($user['nama_lengkap']) . "' 
                                                                                                                                                                                                                                                                                                                                                                                                    data-user-email='" . htmlspecialchars($user['email']) . "'
                                                                                                                                                                                                                                                                                                                                                                                                                                data-user-nohp='" . htmlspecialchars($user['no_hp'] ?? '') . "'>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <i class='bi bi-pencil-fill'></i> Edit Profil
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button class='btn btn-warning' data-bs-toggle='modal' data-bs-target='#resetPasswordModal' data-id-pengguna='{$user['id']}' data-nama-pengguna='" . htmlspecialchars($user['nama_lengkap']) . "'>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <i class='bi bi-key-fill'></i> Reset Password
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {$status_action_link}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </tr>";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                echo "<tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <td colspan='5' class='text-center'>";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (!empty($search_query)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        echo "Pengguna dengan nama atau email \"" . htmlspecialchars($search_query) . "\" tidak ditemukan.";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo "Tidak ada data pengguna.";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            echo "  </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </tr>";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      $stmt_users->close();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      $koneksi->close();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ?>