<?php
/**
 * File: kelola_absensi.php
  * Halaman untuk guru mengambil absensi siswa pada pertemuan tertentu.
   */

   require_once 'config/koneksi.php';

   // Proteksi halaman
   if (!isset($_SESSION['user_id']) || $_SESSION['peran'] != 'guru') {
       header("Location: login.php");
           exit();
           }
           $id_guru = $_SESSION['user_id'];
           $pesan = '';

           // Validasi ID Pertemuan dari URL
           if (!isset($_GET['id_pertemuan'])) {
               header("Location: guru_dashboard.php");
                   exit();
                   }
                   $id_pertemuan = intval($_GET['id_pertemuan']);

                   // Ambil data pertemuan dan verifikasi kepemilikan kelas
                   $stmt_pertemuan = $koneksi->prepare("SELECT p.judul_pertemuan, p.tanggal_pertemuan, k.id as id_kelas FROM pertemuan p JOIN kelas k ON p.id_kelas = k.id WHERE p.id = ? AND k.id_guru = ?");
                   $stmt_pertemuan->bind_param("ii", $id_pertemuan, $id_guru);
                   $stmt_pertemuan->execute();
                   $result_pertemuan = $stmt_pertemuan->get_result();
                   if ($result_pertemuan->num_rows == 0) {
                       header("Location: guru_dashboard.php?error=not_found");
                           exit();
                           }
                           $pertemuan = $result_pertemuan->fetch_assoc();
                           $id_kelas = $pertemuan['id_kelas'];
                           $stmt_pertemuan->close();

                           // Logika untuk menyimpan data absensi
                           if ($_SERVER['REQUEST_METHOD'] == 'POST' && isset($_POST['simpan_absensi'])) {
                               $absensi_data = $_POST['status_absen'];
                                   $stmt_simpan = $koneksi->prepare("INSERT INTO absensi (id_pertemuan, id_siswa, status) VALUES (?, ?, ?) ON DUPLICATE KEY UPDATE status = VALUES(status)");
                                       
                                           foreach ($absensi_data as $id_siswa => $status) {
                                                   $id_siswa_int = intval($id_siswa);
                                                           $stmt_simpan->bind_param("iis", $id_pertemuan, $id_siswa_int, $status);
                                                                   $stmt_simpan->execute();
                                                                       }
                                                                           $stmt_simpan->close();
                                                                               $pesan = "<div class='alert alert-success'>Data absensi berhasil disimpan!</div>";
                                                                               }

                                                                               // Ambil daftar siswa di kelas ini beserta status absensinya (jika sudah ada)
                                                                               $query_siswa = "
                                                                                   SELECT 
                                                                                           u.id, 
                                                                                                   u.nama_lengkap,
                                                                                                           a.status 
                                                                                                               FROM pendaftaran_kelas pk
                                                                                                                   JOIN pengguna u ON pk.id_siswa = u.id
                                                                                                                       LEFT JOIN absensi a ON pk.id_siswa = a.id_siswa AND a.id_pertemuan = ?
                                                                                                                           WHERE pk.id_kelas = ?
                                                                                                                               ORDER BY u.nama_lengkap
                                                                                                                               ";
                                                                                                                               $stmt_siswa = $koneksi->prepare($query_siswa);
                                                                                                                               $stmt_siswa->bind_param("ii", $id_pertemuan, $id_kelas);
                                                                                                                               $stmt_siswa->execute();
                                                                                                                               $result_siswa = $stmt_siswa->get_result();

                                                                                                                               include_once 'templates/header.php';
                                                                                                                               ?>

                                                                                                                               <nav aria-label="breadcrumb">
                                                                                                                                 <ol class="breadcrumb">
                                                                                                                                     <li class="breadcrumb-item"><a href="guru_dashboard.php">Dashboard</a></li>
                                                                                                                                         <li class="breadcrumb-item"><a href="detail_kelas.php?id=<?php echo $id_kelas; ?>">Kelola Kelas</a></li>
                                                                                                                                             <li class="breadcrumb-item active" aria-current="page">Kelola Absensi</li>
                                                                                                                                               </ol>
                                                                                                                                               </nav>

                                                                                                                                               <h1>Absensi: <?php echo htmlspecialchars($pertemuan['judul_pertemuan']); ?></h1>
                                                                                                                                               <p class="text-muted">Tanggal: <?php echo date('d F Y', strtotime($pertemuan['tanggal_pertemuan'])); ?></p>
                                                                                                                                               <hr>

                                                                                                                                               <?php if(!empty($pesan)) echo $pesan; ?>

                                                                                                                                               <form action="kelola_absensi.php?id_pertemuan=<?php echo $id_pertemuan; ?>" method="POST">
                                                                                                                                                   <div class="card">
                                                                                                                                                           <div class="card-header">Daftar Siswa</div>
                                                                                                                                                                   <div class="table-responsive">
                                                                                                                                                                               <table class="table table-striped table-hover mb-0">
                                                                                                                                                                                               <thead>
                                                                                                                                                                                                                   <tr>
                                                                                                                                                                                                                                           <th>Nama Siswa</th>
                                                                                                                                                                                                                                                                   <th class="text-center">Hadir</th>
                                                                                                                                                                                                                                                                                           <th class="text-center">Izin</th>
                                                                                                                                                                                                                                                                                                                   <th class="text-center">Sakit</th>
                                                                                                                                                                                                                                                                                                                                           <th class="text-center">Alfa</th>
                                                                                                                                                                                                                                                                                                                                                               </tr>
                                                                                                                                                                                                                                                                                                                                                                               </thead>
                                                                                                                                                                                                                                                                                                                                                                                               <tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                   <?php while($siswa = $result_siswa->fetch_assoc()): ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                       <tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                               <td><?php echo htmlspecialchars($siswa['nama_lengkap']); ?></td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <?php foreach(['Hadir', 'Izin', 'Sakit', 'Alfa'] as $status): ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               <td class="text-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           <input class="form-check-input" type="radio" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              name="status_absen[<?php echo $siswa['id']; ?>]" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 value="<?php echo $status; ?>" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <?php if ($siswa['status'] == $status) echo 'checked'; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <?php if ($status == 'Alfa' && empty($siswa['status'])) echo 'checked'; // Default ke Alfa jika belum diabsen ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          required>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <?php endforeach; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <?php endwhile; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div class="card-footer text-end">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button type="submit" name="simpan_absensi" class="btn btn-primary">Simpan Absensi</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </form>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <?php
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      $stmt_siswa->close();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      $koneksi->close();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      include_once 'templates/footer.php';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ?>