<?php
require_once 'config/koneksi.php';

// Proteksi, hanya guru yang bisa melakukan aksi
if (!isset($_SESSION['user_id']) || $_SESSION['peran'] != 'guru') {
    header("Location: login.php");
        exit();
        }
        $id_guru = $_SESSION['user_id'];

        // Aksi untuk membuat post baru
        if (isset($_POST['buat_post'])) {
            $judul = sanitize($koneksi, $_POST['judul']);
                $isi_post = $_POST['isi_post']; // Dari CKEditor

                    if (!empty($judul) && !empty($isi_post)) {
                            $stmt = $koneksi->prepare("INSERT INTO kolaborasi_post (id_guru, judul, isi_post) VALUES (?, ?, ?)");
                                    $stmt->bind_param("iss", $id_guru, $judul, $isi_post);
                                            if ($stmt->execute()) {
                                                        header("Location: kolaborasi_index.php?status=post_sukses");
                                                                } else {
                                                                            header("Location: kolaborasi_index.php?status=gagal");
                                                                                    }
                                                                                            $stmt->close();
                                                                                                }
                                                                                                }

                                                                                                // Aksi untuk membuat komentar baru
                                                                                                elseif (isset($_POST['buat_komentar'])) {
                                                                                                    $id_post = intval($_POST['id_post']);
                                                                                                        $isi_komentar = sanitize($koneksi, $_POST['isi_komentar']);

                                                                                                            if (!empty($id_post) && !empty($isi_komentar)) {
                                                                                                                    $stmt = $koneksi->prepare("INSERT INTO kolaborasi_komentar (id_post, id_guru, isi_komentar) VALUES (?, ?, ?)");
                                                                                                                            $stmt->bind_param("iis", $id_post, $id_guru, $isi_komentar);
                                                                                                                                    if ($stmt->execute()) {
                                                                                                                                                header("Location: kolaborasi_post.php?id=" . $id_post);
                                                                                                                                                        } else {
                                                                                                                                                                    header("Location: kolaborasi_post.php?id=" . $id_post . "&status=gagal");
                                                                                                                                                                            }
                                                                                                                                                                                    $stmt->close();
                                                                                                                                                                                        }
                                                                                                                                                                                        }

                                                                                                                                                                                        // ================== LOGIKA BARU DIMULAI DI SINI ==================

                                                                                                                                                                                        // Aksi untuk mengedit post
                                                                                                                                                                                        elseif (isset($_POST['edit_post'])) {
                                                                                                                                                                                            $id_post = intval($_POST['id_post']);
                                                                                                                                                                                                $judul = sanitize($koneksi, $_POST['judul']);
                                                                                                                                                                                                    $isi_post = $_POST['isi_post'];

                                                                                                                                                                                                        if (!empty($id_post) && !empty($judul) && !empty($isi_post)) {
                                                                                                                                                                                                                // Keamanan: pastikan yang mengedit adalah pemilik post
                                                                                                                                                                                                                        $stmt = $koneksi->prepare("UPDATE kolaborasi_post SET judul = ?, isi_post = ? WHERE id = ? AND id_guru = ?");
                                                                                                                                                                                                                                $stmt->bind_param("ssii", $judul, $isi_post, $id_post, $id_guru);
                                                                                                                                                                                                                                        if ($stmt->execute() && $stmt->affected_rows > 0) {
                                                                                                                                                                                                                                                    header("Location: kolaborasi_post.php?id=" . $id_post . "&status=sukses");
                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                        header("Location: kolaborasi_post.php?id=" . $id_post . "&status=gagal");
                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                        $stmt->close();
                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                            // Aksi untuk menghapus post
                                                                                                                                                                                                                                                                                            elseif (isset($_GET['aksi']) && $_GET['aksi'] == 'hapus_post' && isset($_GET['id'])) {
                                                                                                                                                                                                                                                                                                $id_post = intval($_GET['id']);
                                                                                                                                                                                                                                                                                                    // Hapus post dan semua komentarnya (transaksi untuk keamanan)
                                                                                                                                                                                                                                                                                                        $koneksi->begin_transaction();
                                                                                                                                                                                                                                                                                                            try {
                                                                                                                                                                                                                                                                                                                    // Hapus komentar dulu
                                                                                                                                                                                                                                                                                                                            $stmt_komentar = $koneksi->prepare("DELETE FROM kolaborasi_komentar WHERE id_post = ?");
                                                                                                                                                                                                                                                                                                                                    $stmt_komentar->bind_param("i", $id_post);
                                                                                                                                                                                                                                                                                                                                            $stmt_komentar->execute();
                                                                                                                                                                                                                                                                                                                                                    $stmt_komentar->close();
                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                    // Hapus post utama, pastikan hanya pemilik yang bisa hapus
                                                                                                                                                                                                                                                                                                                                                                            $stmt_post = $koneksi->prepare("DELETE FROM kolaborasi_post WHERE id = ? AND id_guru = ?");
                                                                                                                                                                                                                                                                                                                                                                                    $stmt_post->bind_param("ii", $id_post, $id_guru);
                                                                                                                                                                                                                                                                                                                                                                                            $stmt_post->execute();
                                                                                                                                                                                                                                                                                                                                                                                                    $stmt_post->close();

                                                                                                                                                                                                                                                                                                                                                                                                            $koneksi->commit();
                                                                                                                                                                                                                                                                                                                                                                                                                    header("Location: kolaborasi_index.php?status=post_sukses");
                                                                                                                                                                                                                                                                                                                                                                                                                        } catch (Exception $e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                $koneksi->rollback();
                                                                                                                                                                                                                                                                                                                                                                                                                                        header("Location: kolaborasi_index.php?status=gagal");
                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                            // Aksi untuk mengedit komentar
                                                                                                                                                                                                                                                                                                                                                                                                                                            elseif (isset($_POST['edit_komentar'])) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                $id_komentar = intval($_POST['id_komentar']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                    $id_post = intval($_POST['id_post']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                        $isi_komentar = sanitize($koneksi, $_POST['isi_komentar']);

                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (!empty($id_komentar) && !empty($isi_komentar)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Keamanan: pastikan yang mengedit adalah pemilik komentar
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            $stmt = $koneksi->prepare("UPDATE kolaborasi_komentar SET isi_komentar = ? WHERE id = ? AND id_guru = ?");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $stmt->bind_param("sii", $isi_komentar, $id_komentar, $id_guru);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if ($stmt->execute() && $stmt->affected_rows > 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        header("Location: kolaborasi_post.php?id=" . $id_post . "&status=sukses");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            header("Location: kolaborasi_post.php?id=" . $id_post . "&status=gagal");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            $stmt->close();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Aksi untuk menghapus komentar
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                elseif (isset($_GET['aksi']) && $_GET['aksi'] == 'hapus_komentar' && isset($_GET['id'])) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $id_komentar = intval($_GET['id']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        $id_post = intval($_GET['id_post']); // Untuk redirect kembali
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Keamanan: pastikan yang menghapus adalah pemilik komentar
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $stmt = $koneksi->prepare("DELETE FROM kolaborasi_komentar WHERE id = ? AND id_guru = ?");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        $stmt->bind_param("ii", $id_komentar, $id_guru);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if ($stmt->execute() && $stmt->affected_rows > 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    header("Location: kolaborasi_post.php?id=" . $id_post . "&status=sukses");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                header("Location: kolaborasi_post.php?id=" . $id_post . "&status=gagal");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        $stmt->close();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Jika tidak ada aksi yang cocok, kembali ke halaman utama kolaborasi
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            header("Location: kolaborasi_index.php");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            $koneksi->close();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            exit();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ?>