<?php
require_once 'config/koneksi.php';

// Proteksi halaman, hanya untuk guru
if (!isset($_SESSION['user_id']) || $_SESSION['peran'] != 'guru') {
    header("Location: login.php");
        exit();
        }
        include_once 'templates/header.php';

        // Ambil semua data post
        $result_posts = $koneksi->query("
            SELECT 
                    p.id, 
                            p.judul, 
                                    p.waktu_post, 
                                            u.nama_lengkap AS nama_guru,
                                                    (SELECT COUNT(k.id) FROM kolaborasi_komentar k WHERE k.id_post = p.id) AS jumlah_komentar
                                                        FROM kolaborasi_post p
                                                            JOIN pengguna u ON p.id_guru = u.id
                                                                ORDER BY p.waktu_post DESC
                                                                ");
                                                                ?>

                                                                <div class="d-flex justify-content-between align-items-center mb-4">
                                                                    <h1><i class="bi bi-people-fill me-2"></i>Ruang Kolaborasi Guru</h1>
                                                                        <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#buatPostModal">
                                                                                <i class="bi bi-plus-lg me-2"></i>Buat Post Baru
                                                                                    </button>
                                                                                    </div>

                                                                                    <?php 
                                                                                    if (isset($_GET['status'])) {
                                                                                        if ($_GET['status'] == 'post_sukses') {
                                                                                                echo "<div class='alert alert-success'>Postingan baru berhasil dipublikasikan!</div>";
                                                                                                    }
                                                                                                    }
                                                                                                    ?>

                                                                                                    <div class="list-group">
                                                                                                        <?php if ($result_posts && $result_posts->num_rows > 0): ?>
                                                                                                                <?php while($post = $result_posts->fetch_assoc()): ?>
                                                                                                                            <a href="kolaborasi_post.php?id=<?php echo $post['id']; ?>" class="list-group-item list-group-item-action flex-column align-items-start">
                                                                                                                                            <div class="d-flex w-100 justify-content-between">
                                                                                                                                                                <h5 class="mb-1"><?php echo htmlspecialchars($post['judul']); ?></h5>
                                                                                                                                                                                    <small class="text-muted"><?php echo date('d M Y', strtotime($post['waktu_post'])); ?></small>
                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                    <p class="mb-1">
                                                                                                                                                                                                                                        <small>Oleh: <?php echo htmlspecialchars($post['nama_guru']); ?></small>
                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                        <span class="badge bg-primary rounded-pill"><?php echo $post['jumlah_komentar']; ?> Komentar</span>
                                                                                                                                                                                                                                                                                    </a>
                                                                                                                                                                                                                                                                                            <?php endwhile; ?>
                                                                                                                                                                                                                                                                                                <?php else: ?>
                                                                                                                                                                                                                                                                                                        <div class="list-group-item text-center">
                                                                                                                                                                                                                                                                                                                    Belum ada postingan di ruang kolaborasi. Jadilah yang pertama!
                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                <?php endif; ?>
                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                <div class="modal fade" id="buatPostModal" tabindex="-1">
                                                                                                                                                                                                                                                                                                                                    <div class="modal-dialog modal-lg">
                                                                                                                                                                                                                                                                                                                                            <div class="modal-content">
                                                                                                                                                                                                                                                                                                                                                        <div class="modal-header">
                                                                                                                                                                                                                                                                                                                                                                        <h5 class="modal-title">Buat Postingan Baru</h5>
                                                                                                                                                                                                                                                                                                                                                                                        <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                <form action="kolaborasi_aksi.php" method="POST" id="form-post">
                                                                                                                                                                                                                                                                                                                                                                                                                                <div class="modal-body">
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div class="mb-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <label for="judul" class="form-label">Judul Postingan</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <input type="text" class="form-control" name="judul" required>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div class="mb-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <label for="isi_post" class="form-label">Isi Postingan</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <textarea name="isi_post" id="isi_post_editor" class="form-control" rows="10"></textarea>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div class="modal-footer">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Batal</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button type="submit" name="buat_post" class="btn btn-primary">Publikasikan</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <script src="https://cdn.ckeditor.com/4.22.1/standard/ckeditor.js"></script>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <script>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    CKEDITOR.replace('isi_post_editor');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        document.getElementById('form-post').addEventListener('submit', function() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                CKEDITOR.instances.isi_post_editor.updateElement();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </script>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <?php
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $koneksi->close();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    include_once 'templates/footer.php';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ?>