<?php
/**
 * File: login.php
  * Versi Final dengan logo.png
   */
   require_once 'config/koneksi.php';

   // Logika PHP untuk login (tidak ada perubahan)
   if (isset($_SESSION['user_id'])) {
       $peran = $_SESSION['peran'];
           if ($peran == 'admin') { header("Location: admin_dashboard.php"); exit(); }
               elseif ($peran == 'guru') { header("Location: guru_dashboard.php"); exit(); }
                   elseif ($peran == 'siswa') { header("Location: siswa_dashboard.php"); exit(); }
                   }
                   $error = '';
                   if ($_SERVER['REQUEST_METHOD'] == 'POST') {
                       $email = sanitize($koneksi, $_POST['email']);
                           $password = $_POST['password'];
                               if (empty($email) || empty($password)) {
                                       $error = "Email dan password wajib diisi!";
                                           } else {
                                                   $hashed_password = hash('sha256', $password);
                                                           $stmt = $koneksi->prepare("SELECT id, nama_lengkap, peran, status_akun FROM pengguna WHERE email = ? AND password = ?");
                                                                   $stmt->bind_param("ss", $email, $hashed_password);
                                                                           $stmt->execute();
                                                                                   $result = $stmt->get_result();
                                                                                           if ($result->num_rows === 1) {
                                                                                                       $user = $result->fetch_assoc();
                                                                                                                   if ($user['status_akun'] == 'tidak_aktif') {
                                                                                                                                   $error = "Login Gagal. Akun Anda belum diaktifkan oleh Admin.";
                                                                                                                                               } else {
                                                                                                                                                               $_SESSION['user_id'] = $user['id'];
                                                                                                                                                                               $_SESSION['nama_lengkap'] = $user['nama_lengkap'];
                                                                                                                                                                                               $_SESSION['peran'] = $user['peran'];
                                                                                                                                                                                                               if ($user['peran'] == 'admin') { header("Location: admin_dashboard.php"); exit(); }
                                                                                                                                                                                                                               elseif ($user['peran'] == 'guru') { header("Location: guru_dashboard.php"); exit(); }
                                                                                                                                                                                                                                               elseif ($user['peran'] == 'siswa') { header("Location: siswa_dashboard.php"); exit(); }
                                                                                                                                                                                                                                                           }
                                                                                                                                                                                                                                                                   } else {
                                                                                                                                                                                                                                                                               $error = "Login Gagal. Email atau Password salah.";
                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                               $stmt->close();
                                                                                                                                                                                                                                                                                                   }
                                                                                                                                                                                                                                                                                                   }
                                                                                                                                                                                                                                                                                                   $koneksi->close();
                                                                                                                                                                                                                                                                                                   ?>
                                                                                                                                                                                                                                                                                                   <!DOCTYPE html>
                                                                                                                                                                                                                                                                                                   <html lang="id">
                                                                                                                                                                                                                                                                                                   <head>
                                                                                                                                                                                                                                                                                                       <meta charset="UTF-8">
                                                                                                                                                                                                                                                                                                           <meta name="viewport" content="width=device-width, initial-scale=1.0">
                                                                                                                                                                                                                                                                                                               <title>Login - <?php echo htmlspecialchars($PENGATURAN['nama_situs'] ?? 'CAKAP DIGITAL INDONESIA'); ?></title>
                                                                                                                                                                                                                                                                                                                   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
                                                                                                                                                                                                                                                                                                                   </head>
                                                                                                                                                                                                                                                                                                                   <body class="bg-light">
                                                                                                                                                                                                                                                                                                                   <div class="container">
                                                                                                                                                                                                                                                                                                                       <div class="row justify-content-center" style="margin-top: 80px;">
                                                                                                                                                                                                                                                                                                                               <div class="col-md-5 col-lg-4">
                                                                                                                                                                                                                                                                                                                                           <div class="card shadow-sm">
                                                                                                                                                                                                                                                                                                                                                           <div class="card-body p-4">
                                                                                                                                                                                                                                                                                                                                                                               <div class="text-center mb-4">
                                                                                                                                                                                                                                                                                                                                                                                                       <img src="assets/img/logo.png" alt="Logo Cakap Digital" style="width: 100px; height: auto;">
                                                                                                                                                                                                                                                                                                                                                                                                                           </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                               <h3 class="card-title text-center mb-1"><?php echo htmlspecialchars($PENGATURAN['nama_situs'] ?? 'CAKAP DIGITAL INDONESIA'); ?></h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <p class="text-center text-muted mb-4">Silakan login ke akun Anda</p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <?php if (isset($_GET['status']) && $_GET['status'] == 'sukses_daftar'): ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               <div class="alert alert-success">Pendaftaran berhasil! Silakan tunggu aktivasi dari Admin.</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <?php endif; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <?php if ($error): ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               <div class="alert alert-danger"><?php echo $error; ?></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <?php endif; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <form action="login.php" method="POST">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               <div class="mb-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           <label for="email" class="form-label">Alamat Email</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <input type="email" class="form-control" id="email" name="email" required>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <div class="mb-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <label for="password" class="form-label">Password</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               <input type="password" class="form-control" id="password" name="password" required>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               <div class="d-grid">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           <button type="submit" class="btn btn-primary">Login</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           <p class="text-center mt-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <?php if (isset($PENGATURAN['pendaftaran_dibuka']) && $PENGATURAN['pendaftaran_dibuka'] == 1): ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Belum punya akun? <a href="daftar.php">Daftar di sini</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <?php else: ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Pendaftaran ditutup. Hubungi admin.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               <?php endif; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   </body>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   </html>