<?php
require_once 'config/koneksi.php';

// Proteksi halaman, untuk siswa DAN guru
if (!isset($_SESSION['user_id']) || !in_array($_SESSION['peran'], ['siswa', 'guru'])) {
    header("Location: login.php");
        exit();
        }
        $id_pengguna = $_SESSION['user_id'];
        $peran_pengguna = $_SESSION['peran'];

        // Tentukan header yang akan digunakan
        $header_file = ($peran_pengguna == 'guru') ? 'templates/header.php' : 'templates/header_siswa.php';
        include_once $header_file;

        // Logika untuk mengambil daftar kelas berdasarkan peran pengguna
        if ($peran_pengguna == 'siswa') {
            $stmt_kelas_list = $koneksi->prepare("SELECT k.id, k.nama_kelas FROM pendaftaran_kelas pk JOIN kelas k ON pk.id_kelas = k.id WHERE pk.id_siswa = ? ORDER BY k.nama_kelas");
                $stmt_kelas_list->bind_param("i", $id_pengguna);
                } else { // Jika peran adalah guru
                    $stmt_kelas_list = $koneksi->prepare("SELECT id, nama_kelas FROM kelas WHERE id_guru = ? ORDER BY nama_kelas");
                        $stmt_kelas_list->bind_param("i", $id_pengguna);
                        }
                        $stmt_kelas_list->execute();
                        $result_kelas_list = $stmt_kelas_list->get_result();

                        $leaderboard = [];
                        $peringkat_saya = null;
                        $id_kelas_terpilih = null;
                        $info_kelas_terpilih = null;

                        if (isset($_GET['id_kelas']) && !empty($_GET['id_kelas'])) {
                            $id_kelas_terpilih = intval($_GET['id_kelas']);

                                // Ambil info kelas
                                    $stmt_info_kelas = $koneksi->prepare("SELECT nama_kelas FROM kelas WHERE id = ?");
                                        $stmt_info_kelas->bind_param("i", $id_kelas_terpilih);
                                            $stmt_info_kelas->execute();
                                                $info_kelas_terpilih = $stmt_info_kelas->get_result()->fetch_assoc();
                                                    $stmt_info_kelas->close();
                                                        
                                                            // Ambil data peringkat (berdasarkan nilai rata-rata)
                                                                $stmt_leaderboard = $koneksi->prepare("
                                                                        SELECT 
                                                                                    u.nama_lengkap,
                                                                                                (SELECT AVG(p.nilai) FROM penilaian p JOIN soal s ON p.id_soal = s.id WHERE p.id_siswa = u.id AND s.id_kelas = ?) AS rata_rata_nilai
                                                                                                        FROM pendaftaran_kelas pk
                                                                                                                JOIN pengguna u ON pk.id_siswa = u.id
                                                                                                                        WHERE pk.id_kelas = ?
                                                                                                                                ORDER BY rata_rata_nilai DESC, u.nama_lengkap ASC
                                                                                                                                    ");
                                                                                                                                        $stmt_leaderboard->bind_param("ii", $id_kelas_terpilih, $id_kelas_terpilih);
                                                                                                                                            $stmt_leaderboard->execute();
                                                                                                                                                $result_leaderboard = $stmt_leaderboard->get_result();
                                                                                                                                                    while ($row = $result_leaderboard->fetch_assoc()) {
                                                                                                                                                            $leaderboard[] = $row;
                                                                                                                                                                }
                                                                                                                                                                    $stmt_leaderboard->close();

                                                                                                                                                                        // Jika yang melihat adalah siswa, cari peringkatnya
                                                                                                                                                                            if ($peran_pengguna == 'siswa') {
                                                                                                                                                                                    foreach ($leaderboard as $index => $data_siswa) {
                                                                                                                                                                                                if (strcasecmp($data_siswa['nama_lengkap'], $_SESSION['nama_lengkap']) == 0) {
                                                                                                                                                                                                                $peringkat_saya = $index + 1;
                                                                                                                                                                                                                                break;
                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                        ?>

                                                                                                                                                                                                                                                        <h1 class="mb-4 no-print"><i class="bi bi-trophy-fill me-2"></i>Papan Peringkat</h1>

                                                                                                                                                                                                                                                        <div class="card mb-4 no-print">
                                                                                                                                                                                                                                                            <div class="card-body">
                                                                                                                                                                                                                                                                    <form action="papan_peringkat.php" method="GET" class="row g-3 align-items-end">
                                                                                                                                                                                                                                                                                <div class="col-md-5">
                                                                                                                                                                                                                                                                                                <label for="id_kelas" class="form-label">Pilih Kelas</label>
                                                                                                                                                                                                                                                                                                                <select name="id_kelas" id="id_kelas" class="form-select" required>
                                                                                                                                                                                                                                                                                                                                    <option value="">-- Tampilkan Papan Peringkat Kelas --</option>
                                                                                                                                                                                                                                                                                                                                                        <?php mysqli_data_seek($result_kelas_list, 0);
                                                                                                                                                                                                                                                                                                                                                                                  while($kelas = $result_kelas_list->fetch_assoc()): ?>
                                                                                                                                                                                                                                                                                                                                                                                                          <option value="<?php echo $kelas['id']; ?>" <?php if($id_kelas_terpilih == $kelas['id']) echo 'selected'; ?>>
                                                                                                                                                                                                                                                                                                                                                                                                                                      <?php echo htmlspecialchars($kelas['nama_kelas']); ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                              </option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <?php endwhile; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div class="col-auto">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button type="submit" class="btn btn-primary w-100">Tampilkan</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div class="col-auto">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button type="button" class="btn btn-secondary w-100" onclick="window.print();">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <i class="bi bi-printer-fill me-2"></i>Cetak
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <?php if ($id_kelas_terpilih): ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div class="printable-area">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h3 class="text-center mb-3">Papan Peringkat Kelas: <?php echo htmlspecialchars($info_kelas_terpilih['nama_kelas']); ?></h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <?php if ($peran_pengguna == 'siswa' && $peringkat_saya !== null): ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div class="alert alert-info text-center no-print">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <h4>Peringkat Anda saat ini adalah: <strong>#<?php echo $peringkat_saya; ?></strong></h4>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <?php endif; ?>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div class="table-responsive">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <table class="table table-striped table-hover table-bordered">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <thead class="table-light">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <th style="width: 10%;">Peringkat</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <th>Nama Siswa</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <th class="text-center">Rata-rata Nilai</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </thead>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <?php if(count($leaderboard) > 0): ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <?php foreach ($leaderboard as $index => $siswa): ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <?php
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      $rank = $index + 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  $icon = '';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if ($rank == 1) $icon = '🥇';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          elseif ($rank == 2) $icon = '🥈';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      elseif ($rank == 3) $icon = '🥉';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <td class="fw-bold fs-5 text-center"><?php echo $icon; ?> #<?php echo $rank; ?></td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <td><?php echo htmlspecialchars($siswa['nama_lengkap']); ?></td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <td class="text-center fw-bold text-success"><?php echo ($siswa['rata_rata_nilai'] !== null) ? number_format($siswa['rata_rata_nilai'], 2) : 'Belum Ada Nilai'; ?></td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <?php endforeach; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <?php else: ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <td colspan="3" class="text-center">Belum ada aktivitas di kelas ini.</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <?php endif; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <?php endif; ?>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <?php
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              $koneksi->close();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              include_once 'templates/footer.php';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ?>