<?php
require_once 'config/koneksi.php';

// Proteksi halaman, semua pengguna yang login boleh akses
if (!isset($_SESSION['user_id'])) {
    header("Location: login.php");
        exit();
        }
        $id_pengirim = $_SESSION['user_id'];
        $peran_pengirim = $_SESSION['peran'];

        // Tentukan header yang sesuai
        $header_file = 'templates/header.php'; // Default Guru
        if ($peran_pengirim == 'admin') {
            $header_file = 'templates/header_admin.php';
            } elseif ($peran_pengirim == 'siswa') {
                $header_file = 'templates/header_siswa.php';
                }
                include_once $header_file;

                // Logika untuk mengambil daftar penerima berdasarkan peran
                $penerima_options = [];
                if ($peran_pengirim == 'admin') {
                    $penerima_options['semua_guru'] = 'Semua Guru';
                        $penerima_options['semua_siswa'] = 'Semua Siswa';
                            $result_guru = $koneksi->query("SELECT id, nama_lengkap FROM pengguna WHERE peran='guru' ORDER BY nama_lengkap");
                                while ($row = $result_guru->fetch_assoc()) {
                                        $penerima_options['guru-'.$row['id']] = $row['nama_lengkap'] . " (Guru)";
                                            }
                                                $result_siswa = $koneksi->query("SELECT id, nama_lengkap FROM pengguna WHERE peran='siswa' ORDER BY nama_lengkap");
                                                    while ($row = $result_siswa->fetch_assoc()) {
                                                            $penerima_options['siswa-'.$row['id']] = $row['nama_lengkap'] . " (Siswa)";
                                                                }
                                                                } elseif ($peran_pengirim == 'guru') {
                                                                    $result_guru_lain = $koneksi->query("SELECT id, nama_lengkap FROM pengguna WHERE peran='guru' AND id != $id_pengirim ORDER BY nama_lengkap");
                                                                         while ($row = $result_guru_lain->fetch_assoc()) {
                                                                                 $penerima_options['guru-'.$row['id']] = $row['nama_lengkap'] . " (Rekan Guru)";
                                                                                     }
                                                                                         $result_siswa_kelas = $koneksi->query("SELECT u.id, u.nama_lengkap, k.nama_kelas FROM pengguna u JOIN pendaftaran_kelas pk ON u.id = pk.id_siswa JOIN kelas k ON pk.id_kelas = k.id WHERE k.id_guru = $id_pengirim ORDER BY k.nama_kelas, u.nama_lengkap");
                                                                                             while ($row = $result_siswa_kelas->fetch_assoc()) {
                                                                                                     $penerima_options['siswa-'.$row['id']] = $row['nama_lengkap'] . " (" . $row['nama_kelas'] . ")";
                                                                                                         }
                                                                                                         } elseif ($peran_pengirim == 'siswa') {
                                                                                                             // Siswa hanya bisa mengirim ke guru dari kelas yang diikutinya
                                                                                                                 $stmt_guru = $koneksi->prepare("
                                                                                                                         SELECT DISTINCT u.id, u.nama_lengkap 
                                                                                                                                 FROM pengguna u 
                                                                                                                                         JOIN kelas k ON u.id = k.id_guru 
                                                                                                                                                 JOIN pendaftaran_kelas pk ON k.id = pk.id_kelas 
                                                                                                                                                         WHERE pk.id_siswa = ? 
                                                                                                                                                                 ORDER BY u.nama_lengkap
                                                                                                                                                                     ");
                                                                                                                                                                         $stmt_guru->bind_param("i", $id_pengirim);
                                                                                                                                                                             $stmt_guru->execute();
                                                                                                                                                                                 $result_guru = $stmt_guru->get_result();
                                                                                                                                                                                     while ($row = $result_guru->fetch_assoc()) {
                                                                                                                                                                                             $penerima_options['guru-'.$row['id']] = $row['nama_lengkap'] . " (Guru)";
                                                                                                                                                                                                 }
                                                                                                                                                                                                     $stmt_guru->close();
                                                                                                                                                                                                     }
                                                                                                                                                                                                     ?>
                                                                                                                                                                                                     <script src="https://cdn.ckeditor.com/4.22.1/standard/ckeditor.js"></script>

                                                                                                                                                                                                     <h1><i class="bi bi-pencil-square me-2"></i>Tulis Pesan Baru</h1>

                                                                                                                                                                                                     <div class="card">
                                                                                                                                                                                                         <div class="card-body">
                                                                                                                                                                                                                 <form action="pesan_aksi.php" method="POST" id="form-pesan">
                                                                                                                                                                                                                             <div class="mb-3">
                                                                                                                                                                                                                                             <label for="penerima" class="form-label">Kepada</label>
                                                                                                                                                                                                                                                             <select name="penerima[]" id="penerima" class="form-select" multiple required>
                                                                                                                                                                                                                                                                                 <?php if (empty($penerima_options)): ?>
                                                                                                                                                                                                                                                                                                         <option value="" disabled>Anda tidak memiliki guru untuk dikirimi pesan.</option>
                                                                                                                                                                                                                                                                                                                             <?php else: ?>
                                                                                                                                                                                                                                                                                                                                                     <?php foreach ($penerima_options as $value => $label): ?>
                                                                                                                                                                                                                                                                                                                                                                                 <option value="<?php echo $value; ?>"><?php echo htmlspecialchars($label); ?></option>
                                                                                                                                                                                                                                                                                                                                                                                                         <?php endforeach; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                             <?php endif; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                             </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                             <small class="text-muted">Anda dapat memilih lebih dari satu penerima dengan menahan tombol Ctrl (atau Cmd di Mac) dan mengklik nama.</small>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                         </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     <div class="mb-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     <label for="subjek" class="form-label">Subjek</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     <input type="text" name="subjek" id="subjek" class="form-control" required>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             <div class="mb-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             <label for="isi_pesan" class="form-label">Isi Pesan</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             <textarea name="isi_pesan" id="isi_pesan_editor" class="form-control" rows="10"></textarea>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 <div class="text-end">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 <a href="pesan_kotak_masuk.php" class="btn btn-secondary">Batal</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 <button type="submit" name="kirim_pesan" class="btn btn-primary" <?php if (empty($penerima_options)) echo 'disabled'; ?>>Kirim Pesan</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         <script>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             CKEDITOR.replace('isi_pesan_editor');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 document.getElementById('form-pesan').addEventListener('submit', function() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         CKEDITOR.instances.isi_pesan_editor.updateElement();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             </script>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             <?php
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $koneksi->close();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             include_once 'templates/footer.php';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ?>