<?php
/**
 * File: review_kuis.php
  * Halaman untuk siswa melihat kembali jawaban kuis yang telah dikumpulkan.
   */

   require_once 'config/koneksi.php';

   // Proteksi halaman: Pastikan siswa sudah login
   if (!isset($_SESSION['user_id']) || $_SESSION['peran'] != 'siswa') {
       header("Location: login.php");
           exit();
           }
           $id_siswa = $_SESSION['user_id'];

           // Validasi ID Kuis dari URL
           if (!isset($_GET['id_kuis'])) {
               header("Location: siswa_dashboard.php");
                   exit();
                   }
                   $id_kuis = intval($_GET['id_kuis']);

                   // Ambil detail kuis dan verifikasi apakah siswa terdaftar di kelas tersebut
                   $stmt_kuis = $koneksi->prepare("
                       SELECT s.judul_soal, s.deskripsi, k.id as id_kelas, k.nama_kelas
                           FROM soal s
                               JOIN kelas k ON s.id_kelas = k.id
                                   JOIN pendaftaran_kelas pk ON k.id = pk.id_kelas
                                       WHERE s.id = ? AND pk.id_siswa = ?
                                       ");
                                       $stmt_kuis->bind_param("ii", $id_kuis, $id_siswa);
                                       $stmt_kuis->execute();
                                       $result_kuis = $stmt_kuis->get_result();
                                       if ($result_kuis->num_rows == 0) {
                                           // Kuis tidak ditemukan atau siswa tidak berhak mengakses
                                               header("Location: siswa_dashboard.php?error=not_allowed");
                                                   exit();
                                                   }
                                                   $kuis = $result_kuis->fetch_assoc();
                                                   $stmt_kuis->close();

                                                   // Ambil nilai dan komentar yang sudah ada dari tabel penilaian
                                                   $penilaian = null;
                                                   $stmt_penilaian = $koneksi->prepare("SELECT nilai, komentar FROM penilaian WHERE id_soal = ? AND id_siswa = ?");
                                                   $stmt_penilaian->bind_param("ii", $id_kuis, $id_siswa);
                                                   $stmt_penilaian->execute();
                                                   $result_penilaian = $stmt_penilaian->get_result();
                                                   if ($result_penilaian->num_rows > 0) {
                                                       $penilaian = $result_penilaian->fetch_assoc();
                                                       }
                                                       $stmt_penilaian->close();

                                                       // Query untuk mengambil semua pertanyaan di kuis ini dan jawaban siswa terkait
                                                       $query_jawaban = "
                                                           SELECT 
                                                                   bs.soal, bs.tipe_soal, 
                                                                           bs.opsi_a, bs.opsi_b, bs.opsi_c, bs.opsi_d, bs.opsi_e,
                                                                                   bs.kunci_jawaban,
                                                                                           js.jawaban as jawaban_siswa
                                                                                               FROM kuis_soal ks
                                                                                                   JOIN bank_soal bs ON ks.id_bank_soal = bs.id
                                                                                                       LEFT JOIN jawaban_siswa js ON bs.id = js.id_pertanyaan AND js.id_siswa = ? AND js.id_soal = ?
                                                                                                           WHERE ks.id_kuis = ?
                                                                                                               ORDER BY ks.id
                                                                                                               ";
                                                                                                               $stmt_jawaban = $koneksi->prepare($query_jawaban);
                                                                                                               $stmt_jawaban->bind_param("iii", $id_siswa, $id_kuis, $id_kuis);
                                                                                                               $stmt_jawaban->execute();
                                                                                                               $result_jawaban = $stmt_jawaban->get_result();

                                                                                                               include_once 'templates/header_siswa.php';
                                                                                                               ?>

                                                                                                               <nav aria-label="breadcrumb">
                                                                                                                 <ol class="breadcrumb">
                                                                                                                     <li class="breadcrumb-item"><a href="siswa_dashboard.php">Kelas Saya</a></li>
                                                                                                                         <li class="breadcrumb-item"><a href="ruang_kelas_siswa.php?id_kelas=<?php echo $kuis['id_kelas']; ?>"><?php echo htmlspecialchars($kuis['nama_kelas']); ?></a></li>
                                                                                                                             <li class="breadcrumb-item active" aria-current="page">Review Kuis</li>
                                                                                                                               </ol>
                                                                                                                               </nav>

                                                                                                                               <h1 class="mb-2">Review Kuis: <?php echo htmlspecialchars($kuis['judul_soal']); ?></h1>
                                                                                                                               <p class="lead"><?php echo htmlspecialchars($kuis['deskripsi']); ?></p>
                                                                                                                               <hr>

                                                                                                                               <div class="card bg-light mb-4">
                                                                                                                                   <div class="card-body">
                                                                                                                                           <h5 class="card-title">Hasil Penilaian</h5>
                                                                                                                                                   <?php if ($penilaian): ?>
                                                                                                                                                               <p class="card-text mb-1"><strong>Nilai Akhir:</strong> 
                                                                                                                                                                               <span class="fs-4 fw-bold text-primary"><?php echo number_format($penilaian['nilai'], 2); ?></span>
                                                                                                                                                                                           </p>
                                                                                                                                                                                                       <p class="card-text"><strong>Komentar dari Guru:</strong></p>
                                                                                                                                                                                                                   <blockquote class="blockquote mb-0">
                                                                                                                                                                                                                                   <p><?php echo !empty($penilaian['komentar']) ? htmlspecialchars($penilaian['komentar']) : '<em>Tidak ada komentar.</em>'; ?></p>
                                                                                                                                                                                                                                               </blockquote>
                                                                                                                                                                                                                                                       <?php else: ?>
                                                                                                                                                                                                                                                                   <p class="text-muted">Kuis Anda belum dinilai oleh guru.</p>
                                                                                                                                                                                                                                                                           <?php endif; ?>
                                                                                                                                                                                                                                                                               </div>
                                                                                                                                                                                                                                                                               </div>


                                                                                                                                                                                                                                                                               <?php
                                                                                                                                                                                                                                                                               $no_soal = 1;
                                                                                                                                                                                                                                                                               while ($row = $result_jawaban->fetch_assoc()) {
                                                                                                                                                                                                                                                                                   echo "<div class='card mb-3'>";
                                                                                                                                                                                                                                                                                       echo "<div class='card-header'><strong>Pertanyaan #" . $no_soal++ . "</strong></div>";
                                                                                                                                                                                                                                                                                           echo "<div class='card-body'>";
                                                                                                                                                                                                                                                                                               echo "<div class='soal-konten mb-3'>" . $row['soal'] . "</div>"; // Dari CKEditor

                                                                                                                                                                                                                                                                                                   if ($row['tipe_soal'] == 'pilihan_ganda') {
                                                                                                                                                                                                                                                                                                           $jawaban_siswa = strtoupper(trim($row['jawaban_siswa']));
                                                                                                                                                                                                                                                                                                                   $kunci_jawaban = strtoupper(trim($row['kunci_jawaban']));
                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                   echo "<h6>Opsi Jawaban:</h6>";
                                                                                                                                                                                                                                                                                                                                           echo "<ul class='list-group'>";
                                                                                                                                                                                                                                                                                                                                                   foreach (['A', 'B', 'C', 'D', 'E'] as $opsi_huruf) {
                                                                                                                                                                                                                                                                                                                                                               $opsi_teks_key = 'opsi_' . strtolower($opsi_huruf);
                                                                                                                                                                                                                                                                                                                                                                           if (!empty($row[$opsi_teks_key])) {
                                                                                                                                                                                                                                                                                                                                                                                           $class = '';
                                                                                                                                                                                                                                                                                                                                                                                                           $icon = '';
                                                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                                           // Tandai kunci jawaban
                                                                                                                                                                                                                                                                                                                                                                                                                                                           if ($opsi_huruf == $kunci_jawaban) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                               $class = 'list-group-item-success'; // Hijau untuk kunci jawaban
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   $icon = " <i class='bi bi-check-circle-fill text-success'></i> (Kunci Jawaban)";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   // Tandai jawaban siswa
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   if ($opsi_huruf == $jawaban_siswa) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       if ($jawaban_siswa != $kunci_jawaban) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               $class = 'list-group-item-danger'; // Merah jika jawaban siswa salah
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       $icon = " <i class='bi bi-x-circle-fill text-danger'></i> (Jawaban Anda)";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   $icon = " <i class='bi bi-check-circle-fill text-success'></i> (Jawaban Anda Benar)";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo "<li class='list-group-item " . $class . "'>" . $opsi_huruf . ". " . htmlspecialchars($row[$opsi_teks_key]) . $icon . "</li>";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   echo "</ul>";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       } elseif ($row['tipe_soal'] == 'esai') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               echo "<h6>Jawaban Anda:</h6>";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       $jawaban_format = nl2br(htmlspecialchars($row['jawaban_siswa'] ?? 'Tidak menjawab.'));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               echo "<div class='p-3 bg-light border rounded'>" . $jawaban_format . "</div>";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo "</div></div>"; // penutup card-body dan card
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       $stmt_jawaban->close();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       ?>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <div class="text-center mt-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           <a href="ruang_kelas_siswa.php?id_kelas=<?php echo $kuis['id_kelas']; ?>" class="btn btn-secondary">Kembali ke Ruang Kelas</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           </div>


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           <?php
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           $koneksi->close();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           include_once 'templates/footer.php';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ?>