<?php
/**
 * File: simpan_nilai_interaktif.php
  * VERSI PERBAIKAN: Memperbaiki logika penambahan poin agar akurat.
   */

   require_once 'config/koneksi.php';

   if (session_status() == PHP_SESSION_NONE) {
       session_start();
       }

       if (!isset($_SESSION['user_id']) || $_SESSION['peran'] != 'siswa') {
           header('Content-Type: application/json');
               echo json_encode(['status' => 'error', 'message' => 'Akses ditolak.']);
                   exit();
                   }

                   $id_siswa = $_SESSION['user_id'];

                   if (isset($_POST['id_kuis']) && isset($_POST['skor'])) {
                       $id_kuis = intval($_POST['id_kuis']);
                           $nilai_final = floatval($_POST['skor']);

                               $koneksi->begin_transaction();
                                   try {
                                           // 1. Dapatkan nilai lama (jika ada, untuk mencegah duplikasi poin)
                                                   $nilai_lama = 0;
                                                           $stmt_old_nilai = $koneksi->prepare("SELECT nilai FROM penilaian WHERE id_soal = ? AND id_siswa = ?");
                                                                   $stmt_old_nilai->bind_param("ii", $id_kuis, $id_siswa);
                                                                           $stmt_old_nilai->execute();
                                                                                   $result_old = $stmt_old_nilai->get_result();
                                                                                           if ($result_old->num_rows > 0) {
                                                                                                       $nilai_lama = $result_old->fetch_assoc()['nilai'];
                                                                                                               }
                                                                                                                       $stmt_old_nilai->close();

                                                                                                                               // 2. Simpan atau perbarui nilai di tabel penilaian
                                                                                                                                       $komentar = "Penilaian otomatis dari kuis interaktif.";
                                                                                                                                               $stmt_nilai = $koneksi->prepare("INSERT INTO penilaian (id_soal, id_siswa, nilai, komentar) VALUES (?, ?, ?, ?) ON DUPLICATE KEY UPDATE nilai = VALUES(nilai), komentar = VALUES(komentar)");
                                                                                                                                                       $stmt_nilai->bind_param("iids", $id_kuis, $id_siswa, $nilai_final, $komentar);
                                                                                                                                                               $stmt_nilai->execute();
                                                                                                                                                                       $stmt_nilai->close();

                                                                                                                                                                               // 3. Dapatkan id_kelas dan judul kuis
                                                                                                                                                                                       $stmt_kuis_info = $koneksi->prepare("SELECT id_kelas, judul_soal FROM soal WHERE id = ?");
                                                                                                                                                                                               $stmt_kuis_info->bind_param("i", $id_kuis);
                                                                                                                                                                                                       $stmt_kuis_info->execute();
                                                                                                                                                                                                               $result_info = $stmt_kuis_info->get_result()->fetch_assoc();
                                                                                                                                                                                                                       $id_kelas = $result_info['id_kelas'];
                                                                                                                                                                                                                               $judul_kuis = $result_info['judul_soal'];
                                                                                                                                                                                                                                       $stmt_kuis_info->close();

                                                                                                                                                                                                                                               if ($id_kelas) {
                                                                                                                                                                                                                                                           // 4. Hitung selisih poin dan perbarui total poin
                                                                                                                                                                                                                                                                       $selisih_poin = intval($nilai_final) - intval($nilai_lama);
                                                                                                                                                                                                                                                                                   $stmt_total = $koneksi->prepare("INSERT INTO poin_total (id_siswa, id_kelas, total_poin) VALUES (?, ?, ?) ON DUPLICATE KEY UPDATE total_poin = total_poin + ?");
                                                                                                                                                                                                                                                                                               $stmt_total->bind_param("iiii", $id_siswa, $id_kelas, $selisih_poin, $selisih_poin);
                                                                                                                                                                                                                                                                                                           $stmt_total->execute();
                                                                                                                                                                                                                                                                                                                       $stmt_total->close();

                                                                                                                                                                                                                                                                                                                                   // 5. Catat ke log poin jika ada perubahan
                                                                                                                                                                                                                                                                                                                                               if ($selisih_poin != 0) {
                                                                                                                                                                                                                                                                                                                                                               $keterangan = "Menyelesaikan kuis interaktif: '" . $judul_kuis . "'";
                                                                                                                                                                                                                                                                                                                                                                               $stmt_log = $koneksi->prepare("INSERT INTO log_poin (id_siswa, id_kelas, poin, keterangan) VALUES (?, ?, ?, ?)");
                                                                                                                                                                                                                                                                                                                                                                                               $stmt_log->bind_param("iiis", $id_siswa, $id_kelas, $selisih_poin, $keterangan);
                                                                                                                                                                                                                                                                                                                                                                                                               $stmt_log->execute();
                                                                                                                                                                                                                                                                                                                                                                                                                               $stmt_log->close();
                                                                                                                                                                                                                                                                                                                                                                                                                                           }
                                                                                                                                                                                                                                                                                                                                                                                                                                                   }

                                                                                                                                                                                                                                                                                                                                                                                                                                                           $koneksi->commit();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                   header('Content-Type: application/json');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                           echo json_encode(['status' => 'success']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                               } catch (Exception $e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       $koneksi->rollback();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               header('Content-Type: application/json');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo json_encode(['status' => 'error', 'message' => $e->getMessage()]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                header('Content-Type: application/json');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     echo json_encode(['status' => 'error', 'message' => 'Data tidak lengkap']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     $koneksi->close();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ?>