<?php
/**
 * File: siswa_dashboard.php
  * Versi Penuh dan Final
   * PERUBAHAN: Penambahan tombol dan modal untuk fitur "Gabung Kelas".
    */
    require_once 'config/koneksi.php';

    // Proteksi halaman
    if (!isset($_SESSION['user_id']) || $_SESSION['peran'] != 'siswa') {
        header("Location: login.php");
            exit();
            }

            $id_siswa = $_SESSION['user_id'];
            $nama_siswa = $_SESSION['nama_lengkap'];
            $pesan = '';

            // Logika untuk menampilkan notifikasi dari URL
            if (isset($_GET['status'])) {
                if ($_GET['status'] == 'sukses_gabung') {
                        $pesan = "<div class='alert alert-success alert-dismissible fade show' role='alert'>Anda berhasil bergabung ke kelas baru!<button type='button' class='btn-close' data-bs-dismiss='alert' aria-label='Close'></button></div>";
                            } elseif ($_GET['status'] == 'gagal_kode') {
                                    $pesan = "<div class='alert alert-danger alert-dismissible fade show' role='alert'>Gagal! Kode kelas tidak ditemukan atau salah.<button type='button' class='btn-close' data-bs-dismiss='alert' aria-label='Close'></button></div>";
                                        } elseif ($_GET['status'] == 'sudah_terdaftar') {
                                                $pesan = "<div class='alert alert-warning alert-dismissible fade show' role='alert'>Anda sudah terdaftar di kelas tersebut.<button type='button' class='btn-close' data-bs-dismiss='alert' aria-label='Close'></button></div>";
                                                    }
                                                    }


                                                    // Logika untuk mengambil data kelas yang diikuti siswa
                                                    $query_kelas = "
                                                        SELECT 
                                                                k.id, 
                                                                        k.nama_kelas, 
                                                                                k.mata_pelajaran,
                                                                                        k.deskripsi, 
                                                                                                g.nama_lengkap AS nama_guru
                                                                                                    FROM pendaftaran_kelas pk
                                                                                                        JOIN kelas k ON pk.id_kelas = k.id
                                                                                                            JOIN pengguna g ON k.id_guru = g.id
                                                                                                                WHERE pk.id_siswa = ?
                                                                                                                    ORDER BY k.nama_kelas
                                                                                                                    ";

                                                                                                                    $stmt_kelas = $koneksi->prepare($query_kelas);
                                                                                                                    $stmt_kelas->bind_param("i", $id_siswa);
                                                                                                                    $stmt_kelas->execute();
                                                                                                                    $result_kelas = $stmt_kelas->get_result();

                                                                                                                    include_once 'templates/header_siswa.php';
                                                                                                                    ?>

                                                                                                                    <div class="d-flex justify-content-between align-items-center mb-4">
                                                                                                                        <h1 class="mb-0">Kelas Saya</h1>
                                                                                                                            <button class="btn btn-success" data-bs-toggle="modal" data-bs-target="#gabungKelasModal">
                                                                                                                                    <i class="bi bi-plus-circle-fill me-2"></i>Gabung Kelas Baru
                                                                                                                                        </button>
                                                                                                                                        </div>

                                                                                                                                        <p>Selamat datang, <?php echo htmlspecialchars($nama_siswa); ?>! Berikut adalah daftar kelas yang Anda ikuti.</p>

                                                                                                                                        <?php if(!empty($pesan)) echo $pesan; ?>

                                                                                                                                        <div class="row">
                                                                                                                                            <?php if ($result_kelas->num_rows > 0): ?>
                                                                                                                                                    <?php while($kelas = $result_kelas->fetch_assoc()): ?>
                                                                                                                                                            <div class="col-md-4 mb-4">
                                                                                                                                                                        <div class="card h-100 shadow-sm">
                                                                                                                                                                                        <div class="card-body d-flex flex-column">
                                                                                                                                                                                                            <h6 class="card-subtitle mb-2 text-primary fw-bold"><?php echo htmlspecialchars($kelas['mata_pelajaran']); ?></h6>
                                                                                                                                                                                                                                <h5 class="card-title"><?php echo htmlspecialchars($kelas['nama_kelas']); ?></h5>
                                                                                                                                                                                                                                                    <p class="card-text"><small class="text-muted">Guru: <?php echo htmlspecialchars($kelas['nama_guru']); ?></small></p>
                                                                                                                                                                                                                                                                        <p class="card-text flex-grow-1"><?php echo htmlspecialchars(substr($kelas['deskripsi'], 0, 100)); ?>...</p>
                                                                                                                                                                                                                                                                                            <a href="ruang_kelas_siswa.php?id_kelas=<?php echo $kelas['id']; ?>" class="btn btn-primary mt-auto">Masuk Kelas</a>
                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                        <?php endwhile; ?>
                                                                                                                                                                                                                                                                                                                                            <?php else: ?>
                                                                                                                                                                                                                                                                                                                                                    <div class="col-12">
                                                                                                                                                                                                                                                                                                                                                                <div class="alert alert-info">Anda belum terdaftar di kelas mana pun. Klik tombol "Gabung Kelas Baru" untuk mendaftar menggunakan kode dari guru Anda.</div>
                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                            <?php endif; ?>
                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                            <div class="modal fade" id="gabungKelasModal" tabindex="-1" aria-labelledby="gabungKelasModalLabel" aria-hidden="true">
                                                                                                                                                                                                                                                                                                                                                                              <div class="modal-dialog modal-dialog-centered">
                                                                                                                                                                                                                                                                                                                                                                                  <div class="modal-content">
                                                                                                                                                                                                                                                                                                                                                                                        <div class="modal-header">
                                                                                                                                                                                                                                                                                                                                                                                                <h5 class="modal-title" id="gabungKelasModalLabel">Masukkan Kode Kelas</h5>
                                                                                                                                                                                                                                                                                                                                                                                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                    <form action="gabung_kelas_aksi.php" method="POST">
                                                                                                                                                                                                                                                                                                                                                                                                                            <div class="modal-body">
                                                                                                                                                                                                                                                                                                                                                                                                                                        <p>Silakan masukkan 6 digit kode unik yang diberikan oleh guru Anda untuk bergabung ke dalam kelas.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <input type="text" name="kode_kelas" class="form-control text-uppercase" placeholder="KODE KELAS" required maxlength="6" style="font-size: 1.2rem; text-align: center;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div class="modal-footer">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Batal</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button type="submit" name="gabung_kelas" class="btn btn-primary">Gabung</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <?php
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            $stmt_kelas->close();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            $koneksi->close();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            include_once 'templates/footer.php';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ?>